image: rikorose/gcc-cmake:latest

before_script:
 - apt-get update --yes
 - apt-get install --yes libglm-dev
 - apt-get install --yes libsoil-dev
 - apt-get install --yes libglew-dev

stages:
    - build
    - test

build:
    stage: build
    variables:
        CC: gcc
        CXX: g++
    script:
        - cmake -DBUILD_TESTING=ON -Bbuild -H.
        - cmake --build build
    artifacts:
        untracked: true

test:
    stage: test
    script:
        - make test
    dependencies:
        - build
