image: rikorose/gcc-cmake:latest

before_script:
 - apt-get update --yes
 - apt-get install --yes libglm-dev
 - apt-get install --yes libsoil-dev
 - apt-get install --yes libglew-dev

stages:
    - build
    - test
    - package

build:
    stage: build
    variables:
        CC: gcc
        CXX: g++
    script:
        - cmake -DBUILD_TESTING=ON -DBUILD_DOCUMENTATION=OFF -Bbuild -H.
        - cmake --build build --target glge
    artifacts:
        untracked: true

docs:
    stage: build
    script:
        - apt-get install --yes doxygen
        - cmake -DBUILD_TESTING=OFF -DBUILD_DOCUMENTATION=ON -Bbuild -H.
        - cmake --build build --target docs
    artifacts:
        paths:
            - build/html

test:
    stage: test
    script:
        - cmake --build build --target check
    dependencies:
        - build

pages:
    stage: package
    script:
      - mv build/html public/
    artifacts:
      paths:
        - public
    only:
      - master
    dependencies:
      - docs
