image: rikorose/gcc-cmake:latest

stages:
    - build
    - test
    - post-test

build:
    stage: build
    variables:
        CC: gcc
        CXX: g++
    script:
        - apt-get update --yes
        - apt-get install --yes libglm-dev
        - apt-get install --yes libsoil-dev
        - apt-get install --yes libglew-dev
        - cmake -DBUILD_TESTING=OFF -DBUILD_DOCUMENTATION=OFF -G"Unix Makefiles" -Bbuild -DCMAKE_BUILD_TYPE=Release -H.
        - cmake --build build --target glge
    artifacts:
        untracked: true

docs:
    stage: build
    script:
        - apt-get update --yes
        - apt-get install --yes libglm-dev
        - apt-get install --yes libsoil-dev
        - apt-get install --yes libglew-dev
        - apt-get install --yes doxygen
        - cmake -DBUILD_TESTING=OFF -DBUILD_DOCUMENTATION=ON -Bbuild -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -H.
        - cmake --build build --target docs
    artifacts:
        paths:
            - build/html

test:
    stage: test
    script:
        - apt-get update --yes
        - apt-get install --yes libglm-dev
        - apt-get install --yes libsoil-dev
        - apt-get install --yes libglew-dev
        - cmake -DBUILD_TESTING=ON -DGLGE_HEADLESS_TESTS=OFF -DBUILD_DOCUMENTATION=OFF -DCMAKE_BUILD_TYPE=Test -Bbuild -G"Unix Makefiles" -H.
        - cd build
        - cmake --build . --target build_tests
        - ctest
    artifacts:
        untracked: true

memcheck:
    stage: test
    script:
        - apt-get update --yes
        - apt-get install --yes libglm-dev
        - apt-get install --yes libsoil-dev
        - apt-get install --yes libglew-dev
        - apt-get install --yes valgrind
        - cmake -DBUILD_TESTING=ON -DGLGE_HEADLESS_TESTS=OFF -DBUILD_DOCUMENTATION=OFF -DCMAKE_BUILD_TYPE=Debug -Bbuild -G"Unix Makefiles" -H.
        - cd build
        - cmake --build . --target build_tests
        - ctest -T memcheck
    artifacts:
        paths:
            - build/Testing/Temporary/MemoryChecker.*.log

coverage:
    stage: post-test
    script:
        - cd build
        - ctest -T coverage
    dependencies:
        - test

pages:
    stage: post-test
    script:
      - mv build/html public/
    artifacts:
      paths:
        - public
    only:
      - master
    dependencies:
      - docs
